### ISSUE TITLE
GPG errors using latest code on aws through Packer

### ISSUE THREAD

**Issue by adibsaad** [sous-chefs/chef-rvm#358]
I'm getting this when I try to build on aws using ubuntu 14.04 (ami-fce3c696) using Packer and chef-client

my code:

```
include_recipe 'rvm::system_install'
```

output:

```
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `install` on resource 'rvm_installation[root]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
    amazon-ebs: ------------------------------------
    amazon-ebs: Expected process to exit with [0], but received '2'
    amazon-ebs: ---- Begin output of bash /var/chef/cache/rvm-installer-root stable ----
    amazon-ebs: STDOUT: Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
    amazon-ebs: Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
    amazon-ebs: Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
    amazon-ebs: Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
    amazon-ebs:
    amazon-ebs: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.27.0.tgz' - 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc'!
    amazon-ebs: try downloading the signatures:
    amazon-ebs:
    amazon-ebs: sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    amazon-ebs:
    amazon-ebs: or if it fails:
    amazon-ebs:
    amazon-ebs: command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
    amazon-ebs:
    amazon-ebs: the key can be compared with:
    amazon-ebs:
    amazon-ebs: https://rvm.io/mpapis.asc
    amazon-ebs: https://keybase.io/mpapis
    amazon-ebs: STDERR: gpg: directory `/root/.gnupg' created
    amazon-ebs: gpg: new configuration file `/root/.gnupg/gpg.conf' created
    amazon-ebs: gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
    amazon-ebs: gpg: keyring `/root/.gnupg/pubring.gpg' created
    amazon-ebs: gpg: Signature made Tue 29 Mar 2016 01:49:47 PM UTC using RSA key ID BF04FF17
    amazon-ebs: gpg: Can't check signature: public key not found
    amazon-ebs: ---- End output of bash /var/chef/cache/rvm-installer-root stable ----
    amazon-ebs: Ran bash /var/chef/cache/rvm-installer-root stable returned 2
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:156:in `rvm_shell_out!'
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:107:in `run_install_cmd'
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:70:in `install_rvm'
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:63:in `block in converge_install'
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:63:in `converge_install'
    amazon-ebs: /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:50:in `action_install'
    amazon-ebs: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In /var/chef/cache/cookbooks/rvm/recipes/system_install.rb
    amazon-ebs:
    amazon-ebs: 42: rvm_installation("root")
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in /var/chef/cache/cookbooks/rvm/recipes/system_install.rb:42:in `from_file'
    amazon-ebs:
    amazon-ebs: rvm_installation("root") do
    amazon-ebs: provider Chef::Provider::RvmInstallation
    amazon-ebs: action :install
    amazon-ebs: retries 0
    amazon-ebs: retry_delay 2
    amazon-ebs: default_guard_interpreter :default
    amazon-ebs: user "root"
    amazon-ebs: installer_url "https://get.rvm.io"
    amazon-ebs: installer_flags "stable"
    amazon-ebs: install_pkgs ["sed", "grep", "tar", "gzip", "bzip2", "bash", "curl", "git-core"]
    amazon-ebs: rvmrc_template_source "rvmrc.erb"
    amazon-ebs: rvmrc_template_cookbook "rvm"
    amazon-ebs: default_rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
    amazon-ebs: rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
    amazon-ebs: declared_type :rvm_installation
    amazon-ebs: cookbook_name "rvm"
    amazon-ebs: recipe_name "system_install"
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs: Platform:
    amazon-ebs: ---------
    amazon-ebs: x86_64-linux
    amazon-ebs:
    amazon-ebs: [2016-07-06T06:47:48+00:00] INFO: Running queued delayed notifications before re-raising exception
    amazon-ebs: [2016-07-06T06:47:48+00:00] INFO: cookbook_file[/etc/ntp.leapseconds] sending restart action to service[ntp] (delayed)
    amazon-ebs: [2016-07-06T06:47:48+00:00] INFO: Processing service[ntp] action restart (ntp::default line 112)
    amazon-ebs: [2016-07-06T06:47:50+00:00] INFO: service[ntp] restarted
    amazon-ebs: [2016-07-06T06:47:50+00:00] INFO: cookbook_file[/etc/apparmor.d/usr.sbin.ntpd] sending restart action to service[apparmor] (delayed)
    amazon-ebs: [2016-07-06T06:47:50+00:00] INFO: Processing service[apparmor] action restart (ntp::apparmor line 20)
    amazon-ebs: [2016-07-06T06:47:51+00:00] INFO: service[apparmor] restarted
    amazon-ebs: [2016-07-06T06:47:51+00:00] ERROR: Running exception handlers
    amazon-ebs: [2016-07-06T06:47:51+00:00] ERROR: Exception handlers complete
    amazon-ebs: [2016-07-06T06:47:51+00:00] INFO: Sending resource update report (run-id: 9f85d108-0faf-4a0f-b894-e8fe278c6f4c)
    amazon-ebs: [2016-07-06T06:47:51+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    amazon-ebs: [2016-07-06T06:47:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    amazon-ebs: [2016-07-06T06:47:51+00:00] ERROR: rvm_installation[root] (rvm::system_install line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
    amazon-ebs: ---- Begin output of bash /var/chef/cache/rvm-installer-root stable ----
    amazon-ebs: STDOUT: Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
    amazon-ebs: Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
    amazon-ebs: Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
    amazon-ebs: Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
    amazon-ebs:
    amazon-ebs: GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.27.0.tgz' - 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc'!
    amazon-ebs: try downloading the signatures:
    amazon-ebs:
    amazon-ebs: sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    amazon-ebs:
    amazon-ebs: or if it fails:
    amazon-ebs:
    amazon-ebs: command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
    amazon-ebs:
    amazon-ebs: the key can be compared with:
    amazon-ebs:
    amazon-ebs: https://rvm.io/mpapis.asc
    amazon-ebs: https://keybase.io/mpapis
    amazon-ebs: STDERR: gpg: directory `/root/.gnupg' created
    amazon-ebs: gpg: new configuration file `/root/.gnupg/gpg.conf' created
    amazon-ebs: gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
    amazon-ebs: gpg: keyring `/root/.gnupg/pubring.gpg' created
    amazon-ebs: gpg: Signature made Tue 29 Mar 2016 01:49:47 PM UTC using RSA key ID BF04FF17
    amazon-ebs: gpg: Can't check signature: public key not found
    amazon-ebs: ---- End output of bash /var/chef/cache/rvm-installer-root stable ----
    amazon-ebs: Ran bash /var/chef/cache/rvm-installer-root stable returned 2
    amazon-ebs: [2016-07-06T06:47:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

note: recipe works fine on vagrant (even if I use vagrant-aws), but fails using Packer. using latest master.

Thanks!
